"""GENERATED by scripts/generate_packs.py. Safe to edit by hand afterwards.

Regenerating overwrites this file, so move a pack out of SPECS before
hand-editing it long term.
"""

from datetime import date, timedelta
from pathlib import Path

from tests.pack_conformance import run_conformance
from voxgate.packs.loader import load_pack

PACK_DIR = Path(__file__).resolve().parents[1] / "packs" / "realestate_lead"

VALID = {
    "full_name": "Sample answer text here",
    "property_type": "apartment",
    "budget_band": "1m_3m",
    "financing": "cash",
    "move_timeline": "six_months",
    "purpose": "own_use"
}



def test_realestate_lead_conforms():
    run_conformance(load_pack(PACK_DIR), VALID)
