"""GENERATED by scripts/generate_packs.py. Safe to edit by hand afterwards.

Regenerating overwrites this file, so move a pack out of SPECS before
hand-editing it long term.
"""

from datetime import date, timedelta
from pathlib import Path

from tests.pack_conformance import run_conformance
from voxgate.packs.loader import load_pack

PACK_DIR = Path(__file__).resolve().parents[1] / "packs" / "claim_fnol"

VALID = {
    "policy_holder": "Sample answer text here",
    "incident_type": "collision",
    "reported_delay": "same_day",
    "estimated_value": "under_1k",
    "description": "Sample answer text here"
}

VALID["incident_date"] = (date.today() - timedelta(days=int(1.5 * 365.25))).isoformat()


def test_claim_fnol_conforms():
    run_conformance(load_pack(PACK_DIR), VALID)
