"""GENERATED by scripts/generate_packs.py. Safe to edit by hand afterwards.

Regenerating overwrites this file, so move a pack out of SPECS before
hand-editing it long term.
"""

from datetime import date, timedelta
from pathlib import Path

from tests.pack_conformance import run_conformance
from voxgate.packs.loader import load_pack

PACK_DIR = Path(__file__).resolve().parents[1] / "packs" / "support_triage"

VALID = {
    "account_name": "Sample answer text here",
    "issue_area": "other",
    "impact": "annoyance",
    "started": "this_week",
    "tried_already": "Sample answer text here"
}



def test_support_triage_conforms():
    run_conformance(load_pack(PACK_DIR), VALID)
