"""GENERATED by scripts/generate_packs.py. Safe to edit by hand afterwards.

Regenerating overwrites this file, so move a pack out of SPECS before
hand-editing it long term.
"""

from datetime import date, timedelta
from pathlib import Path

from tests.pack_conformance import run_conformance
from voxgate.packs.loader import load_pack

PACK_DIR = Path(__file__).resolve().parents[1] / "packs" / "sales_discovery"

VALID = {
    "company_name": "Sample answer text here",
    "team_size": "1_10",
    "current_tooling": "Sample answer text here",
    "primary_pain": "Sample answer text here",
    "budget_band": "over_50k",
    "timeline": "this_year",
    "decision_role": "decision_maker"
}



def test_sales_discovery_conforms():
    run_conformance(load_pack(PACK_DIR), VALID)
