"""GENERATED by scripts/generate_packs.py. Safe to edit by hand afterwards.

Regenerating overwrites this file, so move a pack out of SPECS before
hand-editing it long term.
"""

from datetime import date, timedelta
from pathlib import Path

from tests.pack_conformance import run_conformance
from voxgate.packs.loader import load_pack

PACK_DIR = Path(__file__).resolve().parents[1] / "packs" / "tenant_screening"

VALID = {
    "full_name": "Sample answer text here",
    "occupants": "one",
    "employment_status": "permanent",
    "rent_to_income": "under_third",
    "tenancy_history": "clean",
    "move_in": "one_month"
}



def test_tenant_screening_conforms():
    run_conformance(load_pack(PACK_DIR), VALID)
