"""GENERATED by scripts/generate_packs.py. Safe to edit by hand afterwards.

Regenerating overwrites this file, so move a pack out of SPECS before
hand-editing it long term.
"""

from datetime import date, timedelta
from pathlib import Path

from tests.pack_conformance import run_conformance
from voxgate.packs.loader import load_pack

PACK_DIR = Path(__file__).resolve().parents[1] / "packs" / "loan_intake"

VALID = {
    "full_name": "Sample answer text here",
    "employment_status": "permanent",
    "income_band": "over_10k",
    "existing_debt": "none",
    "loan_purpose": "home_improvement",
    "residency_years": "over_three"
}



def test_loan_intake_conforms():
    run_conformance(load_pack(PACK_DIR), VALID)
