"""GENERATED by scripts/generate_packs.py. Safe to edit by hand afterwards.

Regenerating overwrites this file, so move a pack out of SPECS before
hand-editing it long term.
"""

from datetime import date, timedelta
from pathlib import Path

from tests.pack_conformance import run_conformance
from voxgate.packs.loader import load_pack

PACK_DIR = Path(__file__).resolve().parents[1] / "packs" / "recruit_screen"

VALID = {
    "full_name": "Sample answer text here",
    "years_experience": "five_to_ten",
    "current_role": "Sample answer text here",
    "notice_period": "one_month",
    "salary_band": "in_band",
    "motivation": "Sample answer text here"
}



def test_recruit_screen_conforms():
    run_conformance(load_pack(PACK_DIR), VALID)
