"""GENERATED by scripts/generate_packs.py. Safe to edit by hand afterwards.

Regenerating overwrites this file, so move a pack out of SPECS before
hand-editing it long term.
"""

from datetime import date, timedelta
from pathlib import Path

from tests.pack_conformance import run_conformance
from voxgate.packs.loader import load_pack

PACK_DIR = Path(__file__).resolve().parents[1] / "packs" / "patient_intake"

VALID = {
    "full_name": "Sample answer text here",
    "primary_symptom": "Sample answer text here",
    "duration": "weeks",
    "severity": "mild",
    "existing_conditions": "Sample answer text here"
}

VALID["dob"] = (date.today() - timedelta(days=int(60.0 * 365.25))).isoformat()


def test_patient_intake_conforms():
    run_conformance(load_pack(PACK_DIR), VALID)
