"""Emit a scenario pack's five files from a declarative spec.

Extracted from scripts/generate_packs.py so the publish endpoint and the CLI
generator share one implementation. A pack created through the UI is therefore
byte-identical to one generated from a spec file, which is the only way the
"every agent is a folder of Python" claim stays literally true.

The emitted code is plain and readable on purpose: these files are shown to
users and are meant to be edited by hand afterwards.
"""

from __future__ import annotations

import json
from pathlib import Path


def _str(value) -> str:
    """Render a string as a Python literal, or refuse.

    `json.dumps` is the whole point. The previous code hand-rolled it as
    `value.replace('"', '\\"')`, which escapes quotes but NOT backslashes — so a
    question containing a backslash followed by a quote emitted a real string
    terminator and dropped the rest of the value into code position. That was a
    working remote code execution through the `question` field, and it was
    worse than the numeric one it sat next to: the generated pack imported
    cleanly, so publish SUCCEEDED, the pack was renamed into the live packs
    directory, and the payload re-ran on every boot.

    Nothing hand-rolled. `json.dumps` escapes backslashes, quotes, newlines and
    control characters, and its output is a valid Python string literal.
    """
    if not isinstance(value, str):
        raise TypeError(f"expected a string, got {type(value).__name__}: {value!r}")
    # ensure_ascii=False matters and is not cosmetic. The default escapes
    # non-ASCII, and for astral characters that means a surrogate PAIR:
    # "🙂" becomes "🙂", which Python source reads back as two lone
    # surrogates rather than the emoji. Every emitted file is written UTF-8 and
    # Python source is UTF-8 by default, so writing the character itself is
    # both correct and readable. Quotes, backslashes, newlines and control
    # characters are still escaped, which is the part that matters for safety.
    return json.dumps(value, ensure_ascii=False)


def _lit(value, indent: int | None = None) -> str:
    """Render a dict or list of strings/numbers as a Python literal.

    Same `ensure_ascii=False` reasoning as `_str`, applied to the structures
    (`flags`, enum `values`, the conformance sample) that go in whole. Keeping
    them on one helper is the point: the escaping bug this file exists to
    prevent came from one call site doing its own thing.
    """
    return json.dumps(value, indent=indent, ensure_ascii=False)


def _num(value) -> str:
    """Render a number as a Python literal, or refuse.

    Bare f-string interpolation of a spec value into generated source is code
    injection: a string like `__import__("os").system("...") or -2.0` in the
    `bias` field became executable at import time. Every numeric interpolation
    goes through here, and a non-number raises rather than being written.

    bool is rejected explicitly because it is a subclass of int and would
    silently emit `True` where a weight belongs.
    """
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise TypeError(f"expected a number, got {type(value).__name__}: {value!r}")
    if value != value or value in (float("inf"), float("-inf")):
        raise ValueError(f"non-finite number: {value!r}")
    return repr(float(value) if isinstance(value, float) else value)


HEADER = '''"""GENERATED by scripts/generate_packs.py. Safe to edit by hand afterwards.

Regenerating overwrites this file, so move a pack out of SPECS before
hand-editing it long term.
"""
'''


def enum_values(field: dict) -> list[str]:
    return list(field["values"])


def emit_schema(spec: dict) -> str:
    lines = [HEADER, "from datetime import date", "",
             "from pydantic import BaseModel, field_validator", "", ""]

    for f in spec["fields"]:
        if f["type"] == "enum":
            const = f"VALID_{f['name'].upper()}"
            # Sorted, not `repr(set(...))`. A set's repr order depends on hash
            # randomisation, so regenerating produced a diff on every run for
            # no reason — which quietly falsified this module's own claim that
            # a pack built here is byte-identical to one built from a spec.
            members = ", ".join(_str(v) for v in sorted(enum_values(f)))
            lines.append(f"{const} = {{{members}}}")
    lines.append("")
    lines.append("")
    lines.append("class Schema(BaseModel):")
    for f in spec["fields"]:
        lines.append(f"    {f['name']}: str")
    lines.append("")

    for f in spec["fields"]:
        name = f["name"]
        if f["type"] == "enum":
            const = f"VALID_{name.upper()}"
            lines += [
                f'    @field_validator("{name}")',
                "    @classmethod",
                f"    def _{name}_valid(cls, v):",
                f"        if v not in {const}:",
                f'            raise ValueError(f"one of {{sorted({const})}}")',
                "        return v",
                "",
            ]
        elif f["type"] == "text":
            min_words = f.get("min_words", 1)
            lines += [
                f'    @field_validator("{name}")',
                "    @classmethod",
                f"    def _{name}_plausible(cls, v):",
                f"        if len(v.split()) < {_num(min_words)}:",
                f'            raise ValueError("needs at least {min_words} word(s)")',
                "        return v",
                "",
            ]
        elif f["type"] == "date":
            lo = f.get("min_age_years", 0)
            hi = f.get("max_age_years", 120)
            lines += [
                f'    @field_validator("{name}")',
                "    @classmethod",
                f"    def _{name}_plausible(cls, v):",
                "        d = date.fromisoformat(v)",
                "        years = (date.today() - d).days / 365.25",
                f"        if not {lo} <= years <= {hi}:",
                f'            raise ValueError("date must be within the last {hi} years")',
                "        return v",
                "",
            ]

    lines.append("")
    lines.append("REASK_HINTS = {")
    for f in spec["fields"]:
        lines.append(f"    {_str(f['name'])}: {_str(f['question'])},")
    lines.append("}")
    return "\n".join(lines) + "\n"


def emit_checks(spec: dict) -> str:
    lines = [HEADER, "from voxgate.packs.base import CheckResult", "", ""]
    lines.append("# Keyword screens. Each returns the phrase it matched, so a reviewer can")
    lines.append("# see what the check actually looked at rather than trusting a number.")
    lines.append("")

    for c in spec["checks"]:
        const = f"_{c['name'].upper()}_FLAGS"
        lines.append(f"{const} = {_lit(c['flags'], indent=4)}")
        lines.append("")
        lines += [
            f"def {c['name']}(fields: dict) -> CheckResult:",
            f"    text = str(fields.get({_str(c['field'])}, '')).lower()",
            f"    for band, score in ((\"hit\", 0.85), (\"review\", 0.45)):",
            f"        for phrase in {const}.get(band, []):",
            "            if phrase in text:",
            "                return CheckResult(",
            f"                    check_name={_str(c['name'])}, status=band, score=score,",
            '                    details={"matched": phrase, "field": '
            f"{_str(c['field'])}}})",
            f"    return CheckResult(check_name={_str(c['name'])}, "
            'status="clear", score=0.0,',
            '                       details={"matched": None, "field": '
            f"{_str(c['field'])}}})",
            # The bare name on the left is a real identifier being defined, so
            # it cannot be quoted; `validate_spec` and the loader both require
            # it to match ^[a-z][a-z0-9_]*$.
            f"{c['name']}.check_name = {_str(c['name'])}",
            "",
            "",
        ]

    names = ", ".join(c["name"] for c in spec["checks"])
    lines.append(f"CHECKS = [{names}]")
    return "\n".join(lines) + "\n"


def emit_scoring(spec: dict) -> str:
    lines = [HEADER, "from voxgate.ml.scorecard import Feature, Scorecard", "", ""]

    weighted = [f for f in spec["fields"] if f["type"] == "enum" and "weight" in f]
    for f in weighted:
        lines.append(f"_{f['name'].upper()}_X = {_lit(f['values'], indent=4)}")
        lines.append("")

    lines += [
        "",
        "def _check_score(data, name):",
        '    return max((c["score"] for c in data["checks"] if c["check_name"] == name),',
        "               default=0.0)",
        "",
        "",
        "def build_scorecard(low, high):",
        "    return Scorecard(",
        "        features=[",
    ]

    for f in weighted:
        lines.append(
            f'            Feature("{f["name"]}_risk", {_num(f["weight"])},\n'
            f'                    lambda d, k="{f["name"]}": '
            f'_{f["name"].upper()}_X[d["fields"][k]]),'
        )
    for c in spec["checks"]:
        lines.append(
            f'            Feature("{c["name"]}_signal", 1.4,\n'
            f'                    lambda d, n="{c["name"]}": _check_score(d, n)),'
        )

    lines += [
        "        ],",
        f"        bias={_num(spec['bias'])}, low_threshold=low, high_threshold=high)",
        "",
        "",
        "FEATURE_FIELD_HINTS = {",
    ]
    for f in weighted:
        lines.append(f'    "{f["name"]}_risk": "{f["name"]}",')
    for c in spec["checks"]:
        lines.append(f'    "{c["name"]}_signal": "{c["field"]}",')
    lines.append("}")
    return "\n".join(lines) + "\n"


def emit_prompt(spec: dict) -> str:
    fields = "\n".join(
        f"- `{f['name']}` — {f['question']}" for f in spec["fields"]
    )
    checks = "\n".join(
        f"- `{c['name']}` reads `{c['field']}`" for c in spec["checks"]
    )
    return f"""# {spec['display_name']}

## Persona

{spec['persona']}

## What you collect

{fields}

## Rules

Ask one question at a time and wait for the answer. If an answer does not fit
the expected values, say what you need and ask once more. Never invent a value
the person did not give you. Never state or imply the outcome: the decision is
made after this conversation, not during it.

## Screening

{checks}

## Gate

Cases route to a **{spec['gate_role']}** when the score is high, or when any
screen returns a hit. In practice that means {spec['gate_reason']}.

## Data

All screening data in this pack is synthetic and marked as such. Nothing here
is a real person, list or record.
"""


def emit_yaml(spec: dict) -> str:
    """pack.yaml, with every scalar quoted.

    Bare interpolation let a newline in `display_name` inject a second YAML
    key. Confirmed: a display name of `Evil\\npack_id: hijacked` produced a file
    whose second `pack_id` won, so the pack loaded under an identity that did
    not match the directory it was written to — and `pack_id` is what the whole
    registry, the API and the graph cache are keyed on.

    Not code execution, but a value the loader trusts completely. `json.dumps`
    output is a valid double-quoted YAML scalar, so one helper covers both the
    generated Python and this file.
    """
    t = spec["thresholds"]
    return (
        f"pack_id: {_str(spec['pack_id'])}\n"
        f"display_name: {_str(spec['display_name'])}\n"
        f"gate_role: {_str(spec['gate_role'])}\n"
        f"thresholds: {{low: {_num(t['low'])}, high: {_num(t['high'])}}}\n"
    )


def sample_fields(spec: dict) -> tuple[dict, dict]:
    """A valid, low-risk applicant for the generated conformance test.

    Returns (literals, date_offsets). Dates are emitted as a runtime expression
    rather than a literal, because a hardcoded date silently ages out of any
    bounded validator. That is exactly what the first generated run got wrong:
    a fixed 2020 date failed claim-fnol's three-year window.
    """
    literals: dict[str, str] = {}
    date_years: dict[str, float] = {}
    for f in spec["fields"]:
        if f["type"] == "enum":
            literals[f["name"]] = min(f["values"], key=lambda k: f["values"][k])
        elif f["type"] == "date":
            lo = f.get("min_age_years", 0)
            hi = f.get("max_age_years", 120)
            # Midpoint of the allowed window, so the sample can never sit on a
            # boundary and can never age out.
            date_years[f["name"]] = round((lo + hi) / 2, 2)
        else:
            literals[f["name"]] = "Sample answer text here"
    return literals, date_years


def emit_test(spec: dict) -> str:
    pid = spec["pack_id"]
    mod = pid.replace("-", "_")
    literals, date_years = sample_fields(spec)

    date_lines = "".join(
        '\nVALID["{}"] = (date.today() - timedelta(days=int({} * 365.25))).isoformat()'.format(
            name, years
        )
        for name, years in date_years.items()
    )

    return f'''{HEADER}
from datetime import date, timedelta
from pathlib import Path

from tests.pack_conformance import run_conformance
from voxgate.packs.loader import load_pack

PACK_DIR = Path(__file__).resolve().parents[1] / "packs" / "{mod}"

VALID = {_lit(literals, indent=4)}
{date_lines}


def test_{mod}_conforms():
    run_conformance(load_pack(PACK_DIR), VALID)
'''


def write_pack(spec: dict, packs_dir: Path, tests_dir: Path | None = None) -> Path:
    """Write one pack's five files. Returns the directory written.

    Shared by the CLI generator and the publish endpoint so a pack created
    through the UI is byte-identical to one generated from a spec file.
    """
    directory = packs_dir / spec["pack_id"].replace("-", "_")
    directory.mkdir(parents=True, exist_ok=True)
    (directory / "pack.yaml").write_text(emit_yaml(spec), encoding="utf-8")
    (directory / "schema.py").write_text(emit_schema(spec), encoding="utf-8")
    (directory / "checks.py").write_text(emit_checks(spec), encoding="utf-8")
    (directory / "scoring.py").write_text(emit_scoring(spec), encoding="utf-8")
    (directory / "prompt.md").write_text(emit_prompt(spec), encoding="utf-8")
    if tests_dir is not None:
        name = spec["pack_id"].replace("-", "_")
        (tests_dir / f"test_pack_{name}.py").write_text(emit_test(spec), encoding="utf-8")
    return directory
