"""GENERATED by scripts/generate_packs.py. Safe to edit by hand afterwards.

Regenerating overwrites this file, so move a pack out of SPECS before
hand-editing it long term.
"""

from voxgate.packs.base import CheckResult


# Keyword screens. Each returns the phrase it matched, so a reviewer can
# see what the check actually looked at rather than trusting a number.

_AFFORDABILITY_STRAIN_FLAGS = {
    "hit": [
        "over_half"
    ],
    "review": [
        "third_to_half"
    ]
}

def affordability_strain(fields: dict) -> CheckResult:
    text = str(fields.get("rent_to_income", '')).lower()
    for band, score in (("hit", 0.85), ("review", 0.45)):
        for phrase in _AFFORDABILITY_STRAIN_FLAGS.get(band, []):
            if phrase in text:
                return CheckResult(
                    check_name="affordability_strain", status=band, score=score,
                    details={"matched": phrase, "field": "rent_to_income"})
    return CheckResult(check_name="affordability_strain", status="clear", score=0.0,
                       details={"matched": None, "field": "rent_to_income"})
affordability_strain.check_name = "affordability_strain"


_HISTORY_FLAG_FLAGS = {
    "hit": [
        "dispute"
    ],
    "review": [
        "first_time"
    ]
}

def history_flag(fields: dict) -> CheckResult:
    text = str(fields.get("tenancy_history", '')).lower()
    for band, score in (("hit", 0.85), ("review", 0.45)):
        for phrase in _HISTORY_FLAG_FLAGS.get(band, []):
            if phrase in text:
                return CheckResult(
                    check_name="history_flag", status=band, score=score,
                    details={"matched": phrase, "field": "tenancy_history"})
    return CheckResult(check_name="history_flag", status="clear", score=0.0,
                       details={"matched": None, "field": "tenancy_history"})
history_flag.check_name = "history_flag"


CHECKS = [affordability_strain, history_flag]
