"""GENERATED by scripts/generate_packs.py. Safe to edit by hand afterwards.

Regenerating overwrites this file, so move a pack out of SPECS before
hand-editing it long term.
"""

from datetime import date

from pydantic import BaseModel, field_validator


VALID_OCCUPANTS = {"five_plus", "one", "three_or_four", "two"}
VALID_EMPLOYMENT_STATUS = {"contract", "permanent", "self_employed", "student", "unemployed"}
VALID_RENT_TO_INCOME = {"over_half", "third_to_half", "under_third"}
VALID_TENANCY_HISTORY = {"clean", "dispute", "first_time"}
VALID_MOVE_IN = {"immediate", "later", "one_month"}


class Schema(BaseModel):
    full_name: str
    occupants: str
    employment_status: str
    rent_to_income: str
    tenancy_history: str
    move_in: str

    @field_validator("full_name")
    @classmethod
    def _full_name_plausible(cls, v):
        if len(v.split()) < 2:
            raise ValueError("needs at least 2 word(s)")
        return v

    @field_validator("occupants")
    @classmethod
    def _occupants_valid(cls, v):
        if v not in VALID_OCCUPANTS:
            raise ValueError(f"one of {sorted(VALID_OCCUPANTS)}")
        return v

    @field_validator("employment_status")
    @classmethod
    def _employment_status_valid(cls, v):
        if v not in VALID_EMPLOYMENT_STATUS:
            raise ValueError(f"one of {sorted(VALID_EMPLOYMENT_STATUS)}")
        return v

    @field_validator("rent_to_income")
    @classmethod
    def _rent_to_income_valid(cls, v):
        if v not in VALID_RENT_TO_INCOME:
            raise ValueError(f"one of {sorted(VALID_RENT_TO_INCOME)}")
        return v

    @field_validator("tenancy_history")
    @classmethod
    def _tenancy_history_valid(cls, v):
        if v not in VALID_TENANCY_HISTORY:
            raise ValueError(f"one of {sorted(VALID_TENANCY_HISTORY)}")
        return v

    @field_validator("move_in")
    @classmethod
    def _move_in_valid(cls, v):
        if v not in VALID_MOVE_IN:
            raise ValueError(f"one of {sorted(VALID_MOVE_IN)}")
        return v


REASK_HINTS = {
    "full_name": "Could I take your full name?",
    "occupants": "How many people would be living in the property?",
    "employment_status": "What is your current employment situation?",
    "rent_to_income": "Roughly what share of your monthly income would the rent be?",
    "tenancy_history": "Have you rented before, and did that tenancy end normally?",
    "move_in": "When would you want to move in?",
}
