"""GENERATED by scripts/generate_packs.py. Safe to edit by hand afterwards.

Regenerating overwrites this file, so move a pack out of SPECS before
hand-editing it long term.
"""

from voxgate.ml.scorecard import Feature, Scorecard


_OCCUPANTS_X = {
    "one": 0.15,
    "two": 0.2,
    "three_or_four": 0.45,
    "five_plus": 0.85
}

_EMPLOYMENT_STATUS_X = {
    "permanent": 0.15,
    "contract": 0.5,
    "self_employed": 0.55,
    "student": 0.7,
    "unemployed": 1.0
}

_RENT_TO_INCOME_X = {
    "under_third": 0.15,
    "third_to_half": 0.5,
    "over_half": 1.0
}

_TENANCY_HISTORY_X = {
    "clean": 0.1,
    "first_time": 0.5,
    "dispute": 1.0
}

_MOVE_IN_X = {
    "immediate": 0.6,
    "one_month": 0.2,
    "later": 0.4
}


def _check_score(data, name):
    return max((c["score"] for c in data["checks"] if c["check_name"] == name),
               default=0.0)


def build_scorecard(low, high):
    return Scorecard(
        features=[
            Feature("occupants_risk", 0.8,
                    lambda d, k="occupants": _OCCUPANTS_X[d["fields"][k]]),
            Feature("employment_status_risk", 1.4,
                    lambda d, k="employment_status": _EMPLOYMENT_STATUS_X[d["fields"][k]]),
            Feature("rent_to_income_risk", 1.8,
                    lambda d, k="rent_to_income": _RENT_TO_INCOME_X[d["fields"][k]]),
            Feature("tenancy_history_risk", 1.5,
                    lambda d, k="tenancy_history": _TENANCY_HISTORY_X[d["fields"][k]]),
            Feature("move_in_risk", 0.7,
                    lambda d, k="move_in": _MOVE_IN_X[d["fields"][k]]),
            Feature("affordability_strain_signal", 1.4,
                    lambda d, n="affordability_strain": _check_score(d, n)),
            Feature("history_flag_signal", 1.4,
                    lambda d, n="history_flag": _check_score(d, n)),
        ],
        bias=-2.4, low_threshold=low, high_threshold=high)


FEATURE_FIELD_HINTS = {
    "occupants_risk": "occupants",
    "employment_status_risk": "employment_status",
    "rent_to_income_risk": "rent_to_income",
    "tenancy_history_risk": "tenancy_history",
    "move_in_risk": "move_in",
    "affordability_strain_signal": "rent_to_income",
    "history_flag_signal": "tenancy_history",
}
