"""GENERATED by scripts/generate_packs.py. Safe to edit by hand afterwards.

Regenerating overwrites this file, so move a pack out of SPECS before
hand-editing it long term.
"""

from voxgate.packs.base import CheckResult


# Keyword screens. Each returns the phrase it matched, so a reviewer can
# see what the check actually looked at rather than trusting a number.

_COMPETITOR_MENTION_FLAGS = {
    "hit": [
        "salesforce",
        "hubspot",
        "outreach",
        "gong"
    ],
    "review": [
        "spreadsheet",
        "excel",
        "manual",
        "nothing"
    ]
}

def competitor_mention(fields: dict) -> CheckResult:
    text = str(fields.get("current_tooling", '')).lower()
    for band, score in (("hit", 0.85), ("review", 0.45)):
        for phrase in _COMPETITOR_MENTION_FLAGS.get(band, []):
            if phrase in text:
                return CheckResult(
                    check_name="competitor_mention", status=band, score=score,
                    details={"matched": phrase, "field": "current_tooling"})
    return CheckResult(check_name="competitor_mention", status="clear", score=0.0,
                       details={"matched": None, "field": "current_tooling"})
competitor_mention.check_name = "competitor_mention"


_URGENCY_SIGNAL_FLAGS = {
    "hit": [
        "losing",
        "churn",
        "audit",
        "fine",
        "deadline",
        "regulator"
    ],
    "review": [
        "slow",
        "manual",
        "expensive",
        "error"
    ]
}

def urgency_signal(fields: dict) -> CheckResult:
    text = str(fields.get("primary_pain", '')).lower()
    for band, score in (("hit", 0.85), ("review", 0.45)):
        for phrase in _URGENCY_SIGNAL_FLAGS.get(band, []):
            if phrase in text:
                return CheckResult(
                    check_name="urgency_signal", status=band, score=score,
                    details={"matched": phrase, "field": "primary_pain"})
    return CheckResult(check_name="urgency_signal", status="clear", score=0.0,
                       details={"matched": None, "field": "primary_pain"})
urgency_signal.check_name = "urgency_signal"


CHECKS = [competitor_mention, urgency_signal]
