"""GENERATED by scripts/generate_packs.py. Safe to edit by hand afterwards.

Regenerating overwrites this file, so move a pack out of SPECS before
hand-editing it long term.
"""

from datetime import date

from pydantic import BaseModel, field_validator


VALID_TEAM_SIZE = {"11_50", "1_10", "51_250", "over_250"}
VALID_BUDGET_BAND = {"10k_50k", "none", "over_50k", "under_10k"}
VALID_TIMELINE = {"no_date", "this_month", "this_quarter", "this_year"}
VALID_DECISION_ROLE = {"decision_maker", "influencer", "researcher"}


class Schema(BaseModel):
    company_name: str
    team_size: str
    current_tooling: str
    primary_pain: str
    budget_band: str
    timeline: str
    decision_role: str

    @field_validator("company_name")
    @classmethod
    def _company_name_plausible(cls, v):
        if len(v.split()) < 1:
            raise ValueError("needs at least 1 word(s)")
        return v

    @field_validator("team_size")
    @classmethod
    def _team_size_valid(cls, v):
        if v not in VALID_TEAM_SIZE:
            raise ValueError(f"one of {sorted(VALID_TEAM_SIZE)}")
        return v

    @field_validator("current_tooling")
    @classmethod
    def _current_tooling_plausible(cls, v):
        if len(v.split()) < 1:
            raise ValueError("needs at least 1 word(s)")
        return v

    @field_validator("primary_pain")
    @classmethod
    def _primary_pain_plausible(cls, v):
        if len(v.split()) < 2:
            raise ValueError("needs at least 2 word(s)")
        return v

    @field_validator("budget_band")
    @classmethod
    def _budget_band_valid(cls, v):
        if v not in VALID_BUDGET_BAND:
            raise ValueError(f"one of {sorted(VALID_BUDGET_BAND)}")
        return v

    @field_validator("timeline")
    @classmethod
    def _timeline_valid(cls, v):
        if v not in VALID_TIMELINE:
            raise ValueError(f"one of {sorted(VALID_TIMELINE)}")
        return v

    @field_validator("decision_role")
    @classmethod
    def _decision_role_valid(cls, v):
        if v not in VALID_DECISION_ROLE:
            raise ValueError(f"one of {sorted(VALID_DECISION_ROLE)}")
        return v


REASK_HINTS = {
    "company_name": "Which company are you calling from?",
    "team_size": "Roughly how many people are in the team that would use this?",
    "current_tooling": "What are you using for this today?",
    "primary_pain": "What is the single biggest problem you are trying to solve?",
    "budget_band": "Is there a budget already set aside for this, and roughly what range?",
    "timeline": "When would you want this working by?",
    "decision_role": "Would you be the one signing this off, or would someone else?",
}
