"""GENERATED by scripts/generate_packs.py. Safe to edit by hand afterwards.

Regenerating overwrites this file, so move a pack out of SPECS before
hand-editing it long term.
"""

from voxgate.ml.scorecard import Feature, Scorecard


_TEAM_SIZE_X = {
    "1_10": 0.2,
    "11_50": 0.4,
    "51_250": 0.7,
    "over_250": 1.0
}

_BUDGET_BAND_X = {
    "none": 1.0,
    "under_10k": 0.6,
    "10k_50k": 0.3,
    "over_50k": 0.1
}

_TIMELINE_X = {
    "this_month": 0.9,
    "this_quarter": 0.5,
    "this_year": 0.3,
    "no_date": 1.0
}

_DECISION_ROLE_X = {
    "decision_maker": 0.1,
    "influencer": 0.5,
    "researcher": 1.0
}


def _check_score(data, name):
    return max((c["score"] for c in data["checks"] if c["check_name"] == name),
               default=0.0)


def build_scorecard(low, high):
    return Scorecard(
        features=[
            Feature("team_size_risk", 1.1,
                    lambda d, k="team_size": _TEAM_SIZE_X[d["fields"][k]]),
            Feature("budget_band_risk", 1.6,
                    lambda d, k="budget_band": _BUDGET_BAND_X[d["fields"][k]]),
            Feature("timeline_risk", 1.4,
                    lambda d, k="timeline": _TIMELINE_X[d["fields"][k]]),
            Feature("decision_role_risk", 1.3,
                    lambda d, k="decision_role": _DECISION_ROLE_X[d["fields"][k]]),
            Feature("competitor_mention_signal", 1.4,
                    lambda d, n="competitor_mention": _check_score(d, n)),
            Feature("urgency_signal_signal", 1.4,
                    lambda d, n="urgency_signal": _check_score(d, n)),
        ],
        bias=-2.4, low_threshold=low, high_threshold=high)


FEATURE_FIELD_HINTS = {
    "team_size_risk": "team_size",
    "budget_band_risk": "budget_band",
    "timeline_risk": "timeline",
    "decision_role_risk": "decision_role",
    "competitor_mention_signal": "current_tooling",
    "urgency_signal_signal": "primary_pain",
}
