"""GENERATED by scripts/generate_packs.py. Safe to edit by hand afterwards.

Regenerating overwrites this file, so move a pack out of SPECS before
hand-editing it long term.
"""

from voxgate.packs.base import CheckResult


# Keyword screens. Each returns the phrase it matched, so a reviewer can
# see what the check actually looked at rather than trusting a number.

_FINANCING_RISK_FLAGS = {
    "hit": [
        "not_arranged"
    ],
    "review": [
        "mortgage_pending"
    ]
}

def financing_risk(fields: dict) -> CheckResult:
    text = str(fields.get("financing", '')).lower()
    for band, score in (("hit", 0.85), ("review", 0.45)):
        for phrase in _FINANCING_RISK_FLAGS.get(band, []):
            if phrase in text:
                return CheckResult(
                    check_name="financing_risk", status=band, score=score,
                    details={"matched": phrase, "field": "financing"})
    return CheckResult(check_name="financing_risk", status="clear", score=0.0,
                       details={"matched": None, "field": "financing"})
financing_risk.check_name = "financing_risk"


_SPECULATION_SIGNAL_FLAGS = {
    "hit": [
        "resale"
    ],
    "review": [
        "investment"
    ]
}

def speculation_signal(fields: dict) -> CheckResult:
    text = str(fields.get("purpose", '')).lower()
    for band, score in (("hit", 0.85), ("review", 0.45)):
        for phrase in _SPECULATION_SIGNAL_FLAGS.get(band, []):
            if phrase in text:
                return CheckResult(
                    check_name="speculation_signal", status=band, score=score,
                    details={"matched": phrase, "field": "purpose"})
    return CheckResult(check_name="speculation_signal", status="clear", score=0.0,
                       details={"matched": None, "field": "purpose"})
speculation_signal.check_name = "speculation_signal"


CHECKS = [financing_risk, speculation_signal]
