"""GENERATED by scripts/generate_packs.py. Safe to edit by hand afterwards.

Regenerating overwrites this file, so move a pack out of SPECS before
hand-editing it long term.
"""

from datetime import date

from pydantic import BaseModel, field_validator


VALID_PROPERTY_TYPE = {"apartment", "commercial", "townhouse", "villa"}
VALID_BUDGET_BAND = {"1m_3m", "500k_1m", "over_3m", "under_500k"}
VALID_FINANCING = {"cash", "mortgage_approved", "mortgage_pending", "not_arranged"}
VALID_MOVE_TIMELINE = {"immediate", "over_a_year", "six_months", "three_months"}
VALID_PURPOSE = {"investment", "own_use", "resale"}


class Schema(BaseModel):
    full_name: str
    property_type: str
    budget_band: str
    financing: str
    move_timeline: str
    purpose: str

    @field_validator("full_name")
    @classmethod
    def _full_name_plausible(cls, v):
        if len(v.split()) < 2:
            raise ValueError("needs at least 2 word(s)")
        return v

    @field_validator("property_type")
    @classmethod
    def _property_type_valid(cls, v):
        if v not in VALID_PROPERTY_TYPE:
            raise ValueError(f"one of {sorted(VALID_PROPERTY_TYPE)}")
        return v

    @field_validator("budget_band")
    @classmethod
    def _budget_band_valid(cls, v):
        if v not in VALID_BUDGET_BAND:
            raise ValueError(f"one of {sorted(VALID_BUDGET_BAND)}")
        return v

    @field_validator("financing")
    @classmethod
    def _financing_valid(cls, v):
        if v not in VALID_FINANCING:
            raise ValueError(f"one of {sorted(VALID_FINANCING)}")
        return v

    @field_validator("move_timeline")
    @classmethod
    def _move_timeline_valid(cls, v):
        if v not in VALID_MOVE_TIMELINE:
            raise ValueError(f"one of {sorted(VALID_MOVE_TIMELINE)}")
        return v

    @field_validator("purpose")
    @classmethod
    def _purpose_valid(cls, v):
        if v not in VALID_PURPOSE:
            raise ValueError(f"one of {sorted(VALID_PURPOSE)}")
        return v


REASK_HINTS = {
    "full_name": "Could I take your full name, please?",
    "property_type": "What kind of property are you looking for?",
    "budget_band": "What price range are you working with?",
    "financing": "Will this be a cash purchase, or are you arranging a mortgage?",
    "move_timeline": "How soon are you hoping to move?",
    "purpose": "Is this to live in yourself, or as an investment?",
}
