"""GENERATED by scripts/generate_packs.py. Safe to edit by hand afterwards.

Regenerating overwrites this file, so move a pack out of SPECS before
hand-editing it long term.
"""

from voxgate.ml.scorecard import Feature, Scorecard


_PROPERTY_TYPE_X = {
    "apartment": 0.2,
    "villa": 0.3,
    "townhouse": 0.3,
    "commercial": 0.7
}

_BUDGET_BAND_X = {
    "under_500k": 0.5,
    "500k_1m": 0.3,
    "1m_3m": 0.2,
    "over_3m": 0.6
}

_FINANCING_X = {
    "cash": 0.15,
    "mortgage_approved": 0.25,
    "mortgage_pending": 0.8,
    "not_arranged": 1.0
}

_MOVE_TIMELINE_X = {
    "immediate": 0.8,
    "three_months": 0.3,
    "six_months": 0.25,
    "over_a_year": 0.7
}

_PURPOSE_X = {
    "own_use": 0.2,
    "investment": 0.5,
    "resale": 0.9
}


def _check_score(data, name):
    return max((c["score"] for c in data["checks"] if c["check_name"] == name),
               default=0.0)


def build_scorecard(low, high):
    return Scorecard(
        features=[
            Feature("property_type_risk", 0.7,
                    lambda d, k="property_type": _PROPERTY_TYPE_X[d["fields"][k]]),
            Feature("budget_band_risk", 1.5,
                    lambda d, k="budget_band": _BUDGET_BAND_X[d["fields"][k]]),
            Feature("financing_risk", 2.0,
                    lambda d, k="financing": _FINANCING_X[d["fields"][k]]),
            Feature("move_timeline_risk", 1.2,
                    lambda d, k="move_timeline": _MOVE_TIMELINE_X[d["fields"][k]]),
            Feature("purpose_risk", 1.0,
                    lambda d, k="purpose": _PURPOSE_X[d["fields"][k]]),
            Feature("financing_risk_signal", 1.4,
                    lambda d, n="financing_risk": _check_score(d, n)),
            Feature("speculation_signal_signal", 1.4,
                    lambda d, n="speculation_signal": _check_score(d, n)),
        ],
        bias=-2.2, low_threshold=low, high_threshold=high)


FEATURE_FIELD_HINTS = {
    "property_type_risk": "property_type",
    "budget_band_risk": "budget_band",
    "financing_risk": "financing",
    "move_timeline_risk": "move_timeline",
    "purpose_risk": "purpose",
    "financing_risk_signal": "financing",
    "speculation_signal_signal": "purpose",
}
