"""GENERATED by scripts/generate_packs.py. Safe to edit by hand afterwards.

Regenerating overwrites this file, so move a pack out of SPECS before
hand-editing it long term.
"""

from voxgate.packs.base import CheckResult


# Keyword screens. Each returns the phrase it matched, so a reviewer can
# see what the check actually looked at rather than trusting a number.

_AFFORDABILITY_FLAGS = {
    "hit": [
        "under_2k"
    ],
    "review": [
        "2k_5k"
    ]
}

def affordability(fields: dict) -> CheckResult:
    text = str(fields.get("income_band", '')).lower()
    for band, score in (("hit", 0.85), ("review", 0.45)):
        for phrase in _AFFORDABILITY_FLAGS.get(band, []):
            if phrase in text:
                return CheckResult(
                    check_name="affordability", status=band, score=score,
                    details={"matched": phrase, "field": "income_band"})
    return CheckResult(check_name="affordability", status="clear", score=0.0,
                       details={"matched": None, "field": "income_band"})
affordability.check_name = "affordability"


_DEBT_STACKING_FLAGS = {
    "hit": [
        "many"
    ],
    "review": [
        "two_or_three"
    ]
}

def debt_stacking(fields: dict) -> CheckResult:
    text = str(fields.get("existing_debt", '')).lower()
    for band, score in (("hit", 0.85), ("review", 0.45)):
        for phrase in _DEBT_STACKING_FLAGS.get(band, []):
            if phrase in text:
                return CheckResult(
                    check_name="debt_stacking", status=band, score=score,
                    details={"matched": phrase, "field": "existing_debt"})
    return CheckResult(check_name="debt_stacking", status="clear", score=0.0,
                       details={"matched": None, "field": "existing_debt"})
debt_stacking.check_name = "debt_stacking"


CHECKS = [affordability, debt_stacking]
