"""GENERATED by scripts/generate_packs.py. Safe to edit by hand afterwards.

Regenerating overwrites this file, so move a pack out of SPECS before
hand-editing it long term.
"""

from datetime import date

from pydantic import BaseModel, field_validator


VALID_EMPLOYMENT_STATUS = {"contract", "permanent", "self_employed", "unemployed"}
VALID_INCOME_BAND = {"2k_5k", "5k_10k", "over_10k", "under_2k"}
VALID_EXISTING_DEBT = {"many", "none", "one", "two_or_three"}
VALID_LOAN_PURPOSE = {"debt_consolidation", "education", "home_improvement", "other", "vehicle"}
VALID_RESIDENCY_YEARS = {"one_to_three", "over_three", "under_1"}


class Schema(BaseModel):
    full_name: str
    employment_status: str
    income_band: str
    existing_debt: str
    loan_purpose: str
    residency_years: str

    @field_validator("full_name")
    @classmethod
    def _full_name_plausible(cls, v):
        if len(v.split()) < 2:
            raise ValueError("needs at least 2 word(s)")
        return v

    @field_validator("employment_status")
    @classmethod
    def _employment_status_valid(cls, v):
        if v not in VALID_EMPLOYMENT_STATUS:
            raise ValueError(f"one of {sorted(VALID_EMPLOYMENT_STATUS)}")
        return v

    @field_validator("income_band")
    @classmethod
    def _income_band_valid(cls, v):
        if v not in VALID_INCOME_BAND:
            raise ValueError(f"one of {sorted(VALID_INCOME_BAND)}")
        return v

    @field_validator("existing_debt")
    @classmethod
    def _existing_debt_valid(cls, v):
        if v not in VALID_EXISTING_DEBT:
            raise ValueError(f"one of {sorted(VALID_EXISTING_DEBT)}")
        return v

    @field_validator("loan_purpose")
    @classmethod
    def _loan_purpose_valid(cls, v):
        if v not in VALID_LOAN_PURPOSE:
            raise ValueError(f"one of {sorted(VALID_LOAN_PURPOSE)}")
        return v

    @field_validator("residency_years")
    @classmethod
    def _residency_years_valid(cls, v):
        if v not in VALID_RESIDENCY_YEARS:
            raise ValueError(f"one of {sorted(VALID_RESIDENCY_YEARS)}")
        return v


REASK_HINTS = {
    "full_name": "Could I take your full name?",
    "employment_status": "What is your current employment situation?",
    "income_band": "Roughly what is your monthly income after tax?",
    "existing_debt": "Do you have other loans or credit commitments at the moment?",
    "loan_purpose": "What would the loan be used for?",
    "residency_years": "How long have you lived at your current address?",
}
