"""GENERATED by scripts/generate_packs.py. Safe to edit by hand afterwards.

Regenerating overwrites this file, so move a pack out of SPECS before
hand-editing it long term.
"""

from voxgate.ml.scorecard import Feature, Scorecard


_EMPLOYMENT_STATUS_X = {
    "permanent": 0.15,
    "contract": 0.45,
    "self_employed": 0.6,
    "unemployed": 1.0
}

_INCOME_BAND_X = {
    "under_2k": 0.9,
    "2k_5k": 0.45,
    "5k_10k": 0.2,
    "over_10k": 0.1
}

_EXISTING_DEBT_X = {
    "none": 0.1,
    "one": 0.35,
    "two_or_three": 0.65,
    "many": 1.0
}

_LOAN_PURPOSE_X = {
    "home_improvement": 0.25,
    "vehicle": 0.3,
    "education": 0.25,
    "debt_consolidation": 0.8,
    "other": 0.6
}

_RESIDENCY_YEARS_X = {
    "under_1": 0.8,
    "one_to_three": 0.4,
    "over_three": 0.15
}


def _check_score(data, name):
    return max((c["score"] for c in data["checks"] if c["check_name"] == name),
               default=0.0)


def build_scorecard(low, high):
    return Scorecard(
        features=[
            Feature("employment_status_risk", 1.6,
                    lambda d, k="employment_status": _EMPLOYMENT_STATUS_X[d["fields"][k]]),
            Feature("income_band_risk", 1.5,
                    lambda d, k="income_band": _INCOME_BAND_X[d["fields"][k]]),
            Feature("existing_debt_risk", 1.7,
                    lambda d, k="existing_debt": _EXISTING_DEBT_X[d["fields"][k]]),
            Feature("loan_purpose_risk", 1.2,
                    lambda d, k="loan_purpose": _LOAN_PURPOSE_X[d["fields"][k]]),
            Feature("residency_years_risk", 0.9,
                    lambda d, k="residency_years": _RESIDENCY_YEARS_X[d["fields"][k]]),
            Feature("affordability_signal", 1.4,
                    lambda d, n="affordability": _check_score(d, n)),
            Feature("debt_stacking_signal", 1.4,
                    lambda d, n="debt_stacking": _check_score(d, n)),
        ],
        bias=-2.5, low_threshold=low, high_threshold=high)


FEATURE_FIELD_HINTS = {
    "employment_status_risk": "employment_status",
    "income_band_risk": "income_band",
    "existing_debt_risk": "existing_debt",
    "loan_purpose_risk": "loan_purpose",
    "residency_years_risk": "residency_years",
    "affordability_signal": "income_band",
    "debt_stacking_signal": "existing_debt",
}
