"""GENERATED by scripts/generate_packs.py. Safe to edit by hand afterwards.

Regenerating overwrites this file, so move a pack out of SPECS before
hand-editing it long term.
"""

from voxgate.packs.base import CheckResult


# Keyword screens. Each returns the phrase it matched, so a reviewer can
# see what the check actually looked at rather than trusting a number.

_SEVERITY_FLAGS = {
    "hit": [
        "outage",
        "blocked"
    ],
    "review": [
        "workaround"
    ]
}

def severity(fields: dict) -> CheckResult:
    text = str(fields.get("impact", '')).lower()
    for band, score in (("hit", 0.85), ("review", 0.45)):
        for phrase in _SEVERITY_FLAGS.get(band, []):
            if phrase in text:
                return CheckResult(
                    check_name="severity", status=band, score=score,
                    details={"matched": phrase, "field": "impact"})
    return CheckResult(check_name="severity", status="clear", score=0.0,
                       details={"matched": None, "field": "impact"})
severity.check_name = "severity"


_CHURN_LANGUAGE_FLAGS = {
    "hit": [
        "cancel",
        "refund",
        "competitor",
        "leaving",
        "lawyer"
    ],
    "review": [
        "frustrated",
        "third time",
        "again",
        "still"
    ]
}

def churn_language(fields: dict) -> CheckResult:
    text = str(fields.get("tried_already", '')).lower()
    for band, score in (("hit", 0.85), ("review", 0.45)):
        for phrase in _CHURN_LANGUAGE_FLAGS.get(band, []):
            if phrase in text:
                return CheckResult(
                    check_name="churn_language", status=band, score=score,
                    details={"matched": phrase, "field": "tried_already"})
    return CheckResult(check_name="churn_language", status="clear", score=0.0,
                       details={"matched": None, "field": "tried_already"})
churn_language.check_name = "churn_language"


CHECKS = [severity, churn_language]
