"""GENERATED by scripts/generate_packs.py. Safe to edit by hand afterwards.

Regenerating overwrites this file, so move a pack out of SPECS before
hand-editing it long term.
"""

from datetime import date

from pydantic import BaseModel, field_validator


VALID_ISSUE_AREA = {"billing", "data", "login", "other", "performance"}
VALID_IMPACT = {"annoyance", "blocked", "outage", "workaround"}
VALID_STARTED = {"longer", "this_week", "today"}


class Schema(BaseModel):
    account_name: str
    issue_area: str
    impact: str
    started: str
    tried_already: str

    @field_validator("account_name")
    @classmethod
    def _account_name_plausible(cls, v):
        if len(v.split()) < 1:
            raise ValueError("needs at least 1 word(s)")
        return v

    @field_validator("issue_area")
    @classmethod
    def _issue_area_valid(cls, v):
        if v not in VALID_ISSUE_AREA:
            raise ValueError(f"one of {sorted(VALID_ISSUE_AREA)}")
        return v

    @field_validator("impact")
    @classmethod
    def _impact_valid(cls, v):
        if v not in VALID_IMPACT:
            raise ValueError(f"one of {sorted(VALID_IMPACT)}")
        return v

    @field_validator("started")
    @classmethod
    def _started_valid(cls, v):
        if v not in VALID_STARTED:
            raise ValueError(f"one of {sorted(VALID_STARTED)}")
        return v

    @field_validator("tried_already")
    @classmethod
    def _tried_already_plausible(cls, v):
        if len(v.split()) < 1:
            raise ValueError("needs at least 1 word(s)")
        return v


REASK_HINTS = {
    "account_name": "Which account are you calling about?",
    "issue_area": "Which part of the product is affected?",
    "impact": "How badly is this affecting your work right now?",
    "started": "When did this start?",
    "tried_already": "What have you already tried?",
}
