"""GENERATED by scripts/generate_packs.py. Safe to edit by hand afterwards.

Regenerating overwrites this file, so move a pack out of SPECS before
hand-editing it long term.
"""

from voxgate.ml.scorecard import Feature, Scorecard


_ISSUE_AREA_X = {
    "login": 0.6,
    "billing": 0.7,
    "data": 0.8,
    "performance": 0.5,
    "other": 0.4
}

_IMPACT_X = {
    "annoyance": 0.15,
    "workaround": 0.4,
    "blocked": 0.85,
    "outage": 1.0
}

_STARTED_X = {
    "today": 0.5,
    "this_week": 0.4,
    "longer": 0.7
}


def _check_score(data, name):
    return max((c["score"] for c in data["checks"] if c["check_name"] == name),
               default=0.0)


def build_scorecard(low, high):
    return Scorecard(
        features=[
            Feature("issue_area_risk", 0.9,
                    lambda d, k="issue_area": _ISSUE_AREA_X[d["fields"][k]]),
            Feature("impact_risk", 1.9,
                    lambda d, k="impact": _IMPACT_X[d["fields"][k]]),
            Feature("started_risk", 0.8,
                    lambda d, k="started": _STARTED_X[d["fields"][k]]),
            Feature("severity_signal", 1.4,
                    lambda d, n="severity": _check_score(d, n)),
            Feature("churn_language_signal", 1.4,
                    lambda d, n="churn_language": _check_score(d, n)),
        ],
        bias=-2.7, low_threshold=low, high_threshold=high)


FEATURE_FIELD_HINTS = {
    "issue_area_risk": "issue_area",
    "impact_risk": "impact",
    "started_risk": "started",
    "severity_signal": "impact",
    "churn_language_signal": "tried_already",
}
