"""GENERATED by scripts/generate_packs.py. Safe to edit by hand afterwards.

Regenerating overwrites this file, so move a pack out of SPECS before
hand-editing it long term.
"""

from voxgate.packs.base import CheckResult


# Keyword screens. Each returns the phrase it matched, so a reviewer can
# see what the check actually looked at rather than trusting a number.

_AVAILABILITY_RISK_FLAGS = {
    "hit": [
        "longer"
    ],
    "review": [
        "three_months"
    ]
}

def availability_risk(fields: dict) -> CheckResult:
    text = str(fields.get("notice_period", '')).lower()
    for band, score in (("hit", 0.85), ("review", 0.45)):
        for phrase in _AVAILABILITY_RISK_FLAGS.get(band, []):
            if phrase in text:
                return CheckResult(
                    check_name="availability_risk", status=band, score=score,
                    details={"matched": phrase, "field": "notice_period"})
    return CheckResult(check_name="availability_risk", status="clear", score=0.0,
                       details={"matched": None, "field": "notice_period"})
availability_risk.check_name = "availability_risk"


_MOTIVATION_FLAGS_FLAGS = {
    "hit": [
        "fired",
        "dismissed",
        "conflict",
        "tribunal"
    ],
    "review": [
        "redundant",
        "restructure",
        "bored",
        "money"
    ]
}

def motivation_flags(fields: dict) -> CheckResult:
    text = str(fields.get("motivation", '')).lower()
    for band, score in (("hit", 0.85), ("review", 0.45)):
        for phrase in _MOTIVATION_FLAGS_FLAGS.get(band, []):
            if phrase in text:
                return CheckResult(
                    check_name="motivation_flags", status=band, score=score,
                    details={"matched": phrase, "field": "motivation"})
    return CheckResult(check_name="motivation_flags", status="clear", score=0.0,
                       details={"matched": None, "field": "motivation"})
motivation_flags.check_name = "motivation_flags"


CHECKS = [availability_risk, motivation_flags]
