"""GENERATED by scripts/generate_packs.py. Safe to edit by hand afterwards.

Regenerating overwrites this file, so move a pack out of SPECS before
hand-editing it long term.
"""

from datetime import date

from pydantic import BaseModel, field_validator


VALID_YEARS_EXPERIENCE = {"five_to_ten", "over_ten", "two_to_five", "under_2"}
VALID_NOTICE_PERIOD = {"immediate", "longer", "one_month", "three_months"}
VALID_SALARY_BAND = {"above_band", "below_band", "in_band", "not_stated"}


class Schema(BaseModel):
    full_name: str
    years_experience: str
    current_role: str
    notice_period: str
    salary_band: str
    motivation: str

    @field_validator("full_name")
    @classmethod
    def _full_name_plausible(cls, v):
        if len(v.split()) < 2:
            raise ValueError("needs at least 2 word(s)")
        return v

    @field_validator("years_experience")
    @classmethod
    def _years_experience_valid(cls, v):
        if v not in VALID_YEARS_EXPERIENCE:
            raise ValueError(f"one of {sorted(VALID_YEARS_EXPERIENCE)}")
        return v

    @field_validator("current_role")
    @classmethod
    def _current_role_plausible(cls, v):
        if len(v.split()) < 1:
            raise ValueError("needs at least 1 word(s)")
        return v

    @field_validator("notice_period")
    @classmethod
    def _notice_period_valid(cls, v):
        if v not in VALID_NOTICE_PERIOD:
            raise ValueError(f"one of {sorted(VALID_NOTICE_PERIOD)}")
        return v

    @field_validator("salary_band")
    @classmethod
    def _salary_band_valid(cls, v):
        if v not in VALID_SALARY_BAND:
            raise ValueError(f"one of {sorted(VALID_SALARY_BAND)}")
        return v

    @field_validator("motivation")
    @classmethod
    def _motivation_plausible(cls, v):
        if len(v.split()) < 3:
            raise ValueError("needs at least 3 word(s)")
        return v


REASK_HINTS = {
    "full_name": "Could I take your full name?",
    "years_experience": "How many years have you worked in this kind of role?",
    "current_role": "What is your current job title?",
    "notice_period": "What notice period would you need to give?",
    "salary_band": "What salary range are you targeting?",
    "motivation": "Why are you looking to move?",
}
