"""GENERATED by scripts/generate_packs.py. Safe to edit by hand afterwards.

Regenerating overwrites this file, so move a pack out of SPECS before
hand-editing it long term.
"""

from voxgate.ml.scorecard import Feature, Scorecard


_YEARS_EXPERIENCE_X = {
    "under_2": 0.8,
    "two_to_five": 0.35,
    "five_to_ten": 0.15,
    "over_ten": 0.2
}

_NOTICE_PERIOD_X = {
    "immediate": 0.3,
    "one_month": 0.2,
    "three_months": 0.7,
    "longer": 1.0
}

_SALARY_BAND_X = {
    "below_band": 0.4,
    "in_band": 0.1,
    "above_band": 0.9,
    "not_stated": 0.6
}


def _check_score(data, name):
    return max((c["score"] for c in data["checks"] if c["check_name"] == name),
               default=0.0)


def build_scorecard(low, high):
    return Scorecard(
        features=[
            Feature("years_experience_risk", 1.3,
                    lambda d, k="years_experience": _YEARS_EXPERIENCE_X[d["fields"][k]]),
            Feature("notice_period_risk", 1.1,
                    lambda d, k="notice_period": _NOTICE_PERIOD_X[d["fields"][k]]),
            Feature("salary_band_risk", 1.5,
                    lambda d, k="salary_band": _SALARY_BAND_X[d["fields"][k]]),
            Feature("availability_risk_signal", 1.4,
                    lambda d, n="availability_risk": _check_score(d, n)),
            Feature("motivation_flags_signal", 1.4,
                    lambda d, n="motivation_flags": _check_score(d, n)),
        ],
        bias=-2.3, low_threshold=low, high_threshold=high)


FEATURE_FIELD_HINTS = {
    "years_experience_risk": "years_experience",
    "notice_period_risk": "notice_period",
    "salary_band_risk": "salary_band",
    "availability_risk_signal": "notice_period",
    "motivation_flags_signal": "motivation",
}
