"""GENERATED by scripts/generate_packs.py. Safe to edit by hand afterwards.

Regenerating overwrites this file, so move a pack out of SPECS before
hand-editing it long term.
"""

from voxgate.packs.base import CheckResult


# Keyword screens. Each returns the phrase it matched, so a reviewer can
# see what the check actually looked at rather than trusting a number.

_RED_FLAG_SYMPTOM_FLAGS = {
    "hit": [
        "chest pain",
        "short of breath",
        "breathing",
        "numbness",
        "slurred",
        "bleeding",
        "fainted",
        "unconscious"
    ],
    "review": [
        "dizzy",
        "headache",
        "fever",
        "vomiting"
    ]
}

def red_flag_symptom(fields: dict) -> CheckResult:
    text = str(fields.get("primary_symptom", '')).lower()
    for band, score in (("hit", 0.85), ("review", 0.45)):
        for phrase in _RED_FLAG_SYMPTOM_FLAGS.get(band, []):
            if phrase in text:
                return CheckResult(
                    check_name="red_flag_symptom", status=band, score=score,
                    details={"matched": phrase, "field": "primary_symptom"})
    return CheckResult(check_name="red_flag_symptom", status="clear", score=0.0,
                       details={"matched": None, "field": "primary_symptom"})
red_flag_symptom.check_name = "red_flag_symptom"


_COMORBIDITY_FLAGS = {
    "hit": [
        "heart",
        "cardiac",
        "stroke",
        "cancer",
        "immunosuppressed"
    ],
    "review": [
        "diabetes",
        "asthma",
        "blood pressure",
        "pregnant"
    ]
}

def comorbidity(fields: dict) -> CheckResult:
    text = str(fields.get("existing_conditions", '')).lower()
    for band, score in (("hit", 0.85), ("review", 0.45)):
        for phrase in _COMORBIDITY_FLAGS.get(band, []):
            if phrase in text:
                return CheckResult(
                    check_name="comorbidity", status=band, score=score,
                    details={"matched": phrase, "field": "existing_conditions"})
    return CheckResult(check_name="comorbidity", status="clear", score=0.0,
                       details={"matched": None, "field": "existing_conditions"})
comorbidity.check_name = "comorbidity"


CHECKS = [red_flag_symptom, comorbidity]
