"""GENERATED by scripts/generate_packs.py. Safe to edit by hand afterwards.

Regenerating overwrites this file, so move a pack out of SPECS before
hand-editing it long term.
"""

from datetime import date

from pydantic import BaseModel, field_validator


VALID_DURATION = {"days", "months", "today", "weeks"}
VALID_SEVERITY = {"mild", "moderate", "severe"}


class Schema(BaseModel):
    full_name: str
    dob: str
    primary_symptom: str
    duration: str
    severity: str
    existing_conditions: str

    @field_validator("full_name")
    @classmethod
    def _full_name_plausible(cls, v):
        if len(v.split()) < 2:
            raise ValueError("needs at least 2 word(s)")
        return v

    @field_validator("dob")
    @classmethod
    def _dob_plausible(cls, v):
        d = date.fromisoformat(v)
        years = (date.today() - d).days / 365.25
        if not 0 <= years <= 120:
            raise ValueError("date must be within the last 120 years")
        return v

    @field_validator("primary_symptom")
    @classmethod
    def _primary_symptom_plausible(cls, v):
        if len(v.split()) < 1:
            raise ValueError("needs at least 1 word(s)")
        return v

    @field_validator("duration")
    @classmethod
    def _duration_valid(cls, v):
        if v not in VALID_DURATION:
            raise ValueError(f"one of {sorted(VALID_DURATION)}")
        return v

    @field_validator("severity")
    @classmethod
    def _severity_valid(cls, v):
        if v not in VALID_SEVERITY:
            raise ValueError(f"one of {sorted(VALID_SEVERITY)}")
        return v

    @field_validator("existing_conditions")
    @classmethod
    def _existing_conditions_plausible(cls, v):
        if len(v.split()) < 1:
            raise ValueError("needs at least 1 word(s)")
        return v


REASK_HINTS = {
    "full_name": "Could you tell me your full name?",
    "dob": "What is your date of birth?",
    "primary_symptom": "What is the main problem you are coming in with?",
    "duration": "How long has this been going on?",
    "severity": "On a scale of mild, moderate or severe, how would you describe it?",
    "existing_conditions": "Do you have any ongoing conditions we should know about?",
}
