"""GENERATED by scripts/generate_packs.py. Safe to edit by hand afterwards.

Regenerating overwrites this file, so move a pack out of SPECS before
hand-editing it long term.
"""

from voxgate.ml.scorecard import Feature, Scorecard


_DURATION_X = {
    "today": 0.8,
    "days": 0.5,
    "weeks": 0.35,
    "months": 0.5
}

_SEVERITY_X = {
    "mild": 0.1,
    "moderate": 0.45,
    "severe": 1.0
}


def _check_score(data, name):
    return max((c["score"] for c in data["checks"] if c["check_name"] == name),
               default=0.0)


def build_scorecard(low, high):
    return Scorecard(
        features=[
            Feature("duration_risk", 1.1,
                    lambda d, k="duration": _DURATION_X[d["fields"][k]]),
            Feature("severity_risk", 1.8,
                    lambda d, k="severity": _SEVERITY_X[d["fields"][k]]),
            Feature("red_flag_symptom_signal", 1.4,
                    lambda d, n="red_flag_symptom": _check_score(d, n)),
            Feature("comorbidity_signal", 1.4,
                    lambda d, n="comorbidity": _check_score(d, n)),
        ],
        bias=-2.9, low_threshold=low, high_threshold=high)


FEATURE_FIELD_HINTS = {
    "duration_risk": "duration",
    "severity_risk": "severity",
    "red_flag_symptom_signal": "primary_symptom",
    "comorbidity_signal": "existing_conditions",
}
