"""GENERATED by scripts/generate_packs.py. Safe to edit by hand afterwards.

Regenerating overwrites this file, so move a pack out of SPECS before
hand-editing it long term.
"""

from voxgate.packs.base import CheckResult


# Keyword screens. Each returns the phrase it matched, so a reviewer can
# see what the check actually looked at rather than trusting a number.

_LATE_REPORT_FLAGS = {
    "hit": [
        "over_a_month"
    ],
    "review": [
        "within_a_month"
    ]
}

def late_report(fields: dict) -> CheckResult:
    text = str(fields.get("reported_delay", '')).lower()
    for band, score in (("hit", 0.85), ("review", 0.45)):
        for phrase in _LATE_REPORT_FLAGS.get(band, []):
            if phrase in text:
                return CheckResult(
                    check_name="late_report", status=band, score=score,
                    details={"matched": phrase, "field": "reported_delay"})
    return CheckResult(check_name="late_report", status="clear", score=0.0,
                       details={"matched": None, "field": "reported_delay"})
late_report.check_name = "late_report"


_NARRATIVE_FLAGS_FLAGS = {
    "hit": [
        "no witness",
        "cash",
        "friend borrowed",
        "cannot remember"
    ],
    "review": [
        "night",
        "alone",
        "unlit",
        "no cctv"
    ]
}

def narrative_flags(fields: dict) -> CheckResult:
    text = str(fields.get("description", '')).lower()
    for band, score in (("hit", 0.85), ("review", 0.45)):
        for phrase in _NARRATIVE_FLAGS_FLAGS.get(band, []):
            if phrase in text:
                return CheckResult(
                    check_name="narrative_flags", status=band, score=score,
                    details={"matched": phrase, "field": "description"})
    return CheckResult(check_name="narrative_flags", status="clear", score=0.0,
                       details={"matched": None, "field": "description"})
narrative_flags.check_name = "narrative_flags"


CHECKS = [late_report, narrative_flags]
