"""GENERATED by scripts/generate_packs.py. Safe to edit by hand afterwards.

Regenerating overwrites this file, so move a pack out of SPECS before
hand-editing it long term.
"""

from datetime import date

from pydantic import BaseModel, field_validator


VALID_INCIDENT_TYPE = {"collision", "fire", "theft", "third_party", "water"}
VALID_REPORTED_DELAY = {"over_a_month", "same_day", "within_a_month", "within_a_week"}
VALID_ESTIMATED_VALUE = {"10k_50k", "1k_10k", "over_50k", "under_1k"}


class Schema(BaseModel):
    policy_holder: str
    incident_date: str
    incident_type: str
    reported_delay: str
    estimated_value: str
    description: str

    @field_validator("policy_holder")
    @classmethod
    def _policy_holder_plausible(cls, v):
        if len(v.split()) < 2:
            raise ValueError("needs at least 2 word(s)")
        return v

    @field_validator("incident_date")
    @classmethod
    def _incident_date_plausible(cls, v):
        d = date.fromisoformat(v)
        years = (date.today() - d).days / 365.25
        if not 0 <= years <= 3:
            raise ValueError("date must be within the last 3 years")
        return v

    @field_validator("incident_type")
    @classmethod
    def _incident_type_valid(cls, v):
        if v not in VALID_INCIDENT_TYPE:
            raise ValueError(f"one of {sorted(VALID_INCIDENT_TYPE)}")
        return v

    @field_validator("reported_delay")
    @classmethod
    def _reported_delay_valid(cls, v):
        if v not in VALID_REPORTED_DELAY:
            raise ValueError(f"one of {sorted(VALID_REPORTED_DELAY)}")
        return v

    @field_validator("estimated_value")
    @classmethod
    def _estimated_value_valid(cls, v):
        if v not in VALID_ESTIMATED_VALUE:
            raise ValueError(f"one of {sorted(VALID_ESTIMATED_VALUE)}")
        return v

    @field_validator("description")
    @classmethod
    def _description_plausible(cls, v):
        if len(v.split()) < 4:
            raise ValueError("needs at least 4 word(s)")
        return v


REASK_HINTS = {
    "policy_holder": "What is the name on the policy?",
    "incident_date": "What date did the incident happen?",
    "incident_type": "What kind of incident was it?",
    "reported_delay": "How long after it happened are you reporting this?",
    "estimated_value": "Roughly what do you think the loss is worth?",
    "description": "In your own words, what happened?",
}
