"""GENERATED by scripts/generate_packs.py. Safe to edit by hand afterwards.

Regenerating overwrites this file, so move a pack out of SPECS before
hand-editing it long term.
"""

from voxgate.ml.scorecard import Feature, Scorecard


_INCIDENT_TYPE_X = {
    "collision": 0.4,
    "theft": 0.8,
    "fire": 0.7,
    "water": 0.4,
    "third_party": 0.5
}

_REPORTED_DELAY_X = {
    "same_day": 0.1,
    "within_a_week": 0.3,
    "within_a_month": 0.7,
    "over_a_month": 1.0
}

_ESTIMATED_VALUE_X = {
    "under_1k": 0.15,
    "1k_10k": 0.35,
    "10k_50k": 0.7,
    "over_50k": 1.0
}


def _check_score(data, name):
    return max((c["score"] for c in data["checks"] if c["check_name"] == name),
               default=0.0)


def build_scorecard(low, high):
    return Scorecard(
        features=[
            Feature("incident_type_risk", 1.2,
                    lambda d, k="incident_type": _INCIDENT_TYPE_X[d["fields"][k]]),
            Feature("reported_delay_risk", 1.7,
                    lambda d, k="reported_delay": _REPORTED_DELAY_X[d["fields"][k]]),
            Feature("estimated_value_risk", 1.4,
                    lambda d, k="estimated_value": _ESTIMATED_VALUE_X[d["fields"][k]]),
            Feature("late_report_signal", 1.4,
                    lambda d, n="late_report": _check_score(d, n)),
            Feature("narrative_flags_signal", 1.4,
                    lambda d, n="narrative_flags": _check_score(d, n)),
        ],
        bias=-2.6, low_threshold=low, high_threshold=high)


FEATURE_FIELD_HINTS = {
    "incident_type_risk": "incident_type",
    "reported_delay_risk": "reported_delay",
    "estimated_value_risk": "estimated_value",
    "late_report_signal": "reported_delay",
    "narrative_flags_signal": "description",
}
